import java.awt.Color;
import static java.awt.Color.green;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 628037
 */
public class PersonalityQuiz extends javax.swing.JFrame {
    int score = 0;
    /**
     * Creates new form PersonalityQuiz
     */
    public PersonalityQuiz() {
        initComponents();   
        try {
            File file = new File("scores.txt");
            Scanner sc = new Scanner(file);
            String scorestxt = sc.nextLine();
            ranking.setText(scorestxt);
        } 
        catch (FileNotFoundException e) {
            System.out.println("File not found");   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        question2 = new javax.swing.JLabel();
        question3 = new javax.swing.JLabel();
        question4 = new javax.swing.JLabel();
        question5 = new javax.swing.JLabel();
        question6 = new javax.swing.JLabel();
        question7 = new javax.swing.JLabel();
        question8 = new javax.swing.JLabel();
        question9 = new javax.swing.JLabel();
        question10 = new javax.swing.JLabel();
        answerA1 = new javax.swing.JButton();
        answerA2 = new javax.swing.JButton();
        answerA3 = new javax.swing.JButton();
        answerA4 = new javax.swing.JButton();
        answerA5 = new javax.swing.JButton();
        answerA6 = new javax.swing.JButton();
        answerA7 = new javax.swing.JButton();
        answerA8 = new javax.swing.JButton();
        answerA9 = new javax.swing.JButton();
        answerA10 = new javax.swing.JButton();
        answerB1 = new javax.swing.JButton();
        answerB2 = new javax.swing.JButton();
        answerB3 = new javax.swing.JButton();
        answerB4 = new javax.swing.JButton();
        answerB5 = new javax.swing.JButton();
        answerB6 = new javax.swing.JButton();
        answerB7 = new javax.swing.JButton();
        answerB8 = new javax.swing.JButton();
        answerB9 = new javax.swing.JButton();
        answerB10 = new javax.swing.JButton();
        answerC1 = new javax.swing.JButton();
        answerC2 = new javax.swing.JButton();
        answerC3 = new javax.swing.JButton();
        answerC4 = new javax.swing.JButton();
        answerC5 = new javax.swing.JButton();
        answerC6 = new javax.swing.JButton();
        answerC7 = new javax.swing.JButton();
        answerC8 = new javax.swing.JButton();
        answerC9 = new javax.swing.JButton();
        answerC10 = new javax.swing.JButton();
        answrD1 = new javax.swing.JButton();
        answerD2 = new javax.swing.JButton();
        answrD3 = new javax.swing.JButton();
        answrD4 = new javax.swing.JButton();
        answrD5 = new javax.swing.JButton();
        answrD6 = new javax.swing.JButton();
        answrD7 = new javax.swing.JButton();
        answrD8 = new javax.swing.JButton();
        answrD9 = new javax.swing.JButton();
        answrD10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ranking = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        nameBox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 153));
        setForeground(new java.awt.Color(211, 204, 179));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText(" PERIODIC TABLE QUIZ ");
        jLabel1.setOpaque(true);

        question1.setBackground(new java.awt.Color(255, 255, 255));
        question1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        question1.setForeground(new java.awt.Color(153, 0, 255));
        question1.setText(" WHICH ELEMENT HAS THE SYMBOL K? ");
        question1.setOpaque(true);

        question2.setBackground(new java.awt.Color(255, 255, 255));
        question2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        question2.setForeground(new java.awt.Color(153, 0, 255));
        question2.setText(" WHICH ELEMENT HAS THE SYMBOL AU? ");
        question2.setOpaque(true);

        question3.setBackground(new java.awt.Color(255, 255, 255));
        question3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        question3.setForeground(new java.awt.Color(153, 0, 255));
        question3.setText(" WHICH ELEMENT HAS THE SYMBOL W? ");
        question3.setOpaque(true);

        question4.setBackground(new java.awt.Color(255, 255, 255));
        question4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        question4.setForeground(new java.awt.Color(153, 0, 255));
        question4.setText(" WHICH ELEMENT HAS THE SYMBOL CO? ");
        question4.setOpaque(true);

        question5.setBackground(new java.awt.Color(255, 255, 255));
        question5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        question5.setForeground(new java.awt.Color(153, 51, 255));
        question5.setText(" WHICH ELEMENT HAS THE SYMBOL MN? ");
        question5.setOpaque(true);

        question6.setBackground(new java.awt.Color(255, 255, 255));
        question6.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        question6.setForeground(new java.awt.Color(153, 0, 255));
        question6.setText(" WHICH ELEMENT HAS THE SYMBOL CN? ");
        question6.setOpaque(true);

        question7.setBackground(new java.awt.Color(255, 255, 255));
        question7.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        question7.setForeground(new java.awt.Color(153, 0, 255));
        question7.setText(" WHICH ELEMENT HAS THE SYMBOL RA? ");
        question7.setOpaque(true);

        question8.setBackground(new java.awt.Color(255, 255, 255));
        question8.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        question8.setForeground(new java.awt.Color(153, 0, 255));
        question8.setText(" WHICH ELEMENT HAS THE SYMBOL P? ");
        question8.setOpaque(true);

        question9.setBackground(new java.awt.Color(255, 255, 255));
        question9.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        question9.setForeground(new java.awt.Color(153, 0, 255));
        question9.setText(" WHICH ELEMENT HAS THE SYMBOL B? ");
        question9.setOpaque(true);

        question10.setBackground(new java.awt.Color(255, 255, 255));
        question10.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        question10.setForeground(new java.awt.Color(153, 51, 255));
        question10.setText(" WHICH ELEMENT HAS THE SYMBOL HG? ");
        question10.setOpaque(true);

        answerA1.setBackground(new java.awt.Color(255, 255, 255));
        answerA1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerA1.setForeground(new java.awt.Color(153, 0, 255));
        answerA1.setText("Krypton");
        answerA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerA1ActionPerformed(evt);
            }
        });

        answerA2.setBackground(new java.awt.Color(255, 255, 255));
        answerA2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerA2.setForeground(new java.awt.Color(153, 0, 255));
        answerA2.setText("SILVER");
        answerA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerA2ActionPerformed(evt);
            }
        });

        answerA3.setBackground(new java.awt.Color(255, 255, 255));
        answerA3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerA3.setForeground(new java.awt.Color(153, 0, 255));
        answerA3.setText("YTTRIUM");
        answerA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerA3ActionPerformed(evt);
            }
        });

        answerA4.setBackground(new java.awt.Color(255, 255, 255));
        answerA4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerA4.setForeground(new java.awt.Color(153, 0, 255));
        answerA4.setText("CHROMIUM");
        answerA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerA4ActionPerformed(evt);
            }
        });

        answerA5.setBackground(new java.awt.Color(255, 255, 255));
        answerA5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerA5.setForeground(new java.awt.Color(153, 51, 255));
        answerA5.setText("MAGNESIUM");
        answerA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerA5ActionPerformed(evt);
            }
        });

        answerA6.setBackground(new java.awt.Color(255, 255, 255));
        answerA6.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerA6.setForeground(new java.awt.Color(153, 0, 255));
        answerA6.setText("CALIFORNIUM");
        answerA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerA6ActionPerformed(evt);
            }
        });

        answerA7.setBackground(new java.awt.Color(255, 255, 255));
        answerA7.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerA7.setForeground(new java.awt.Color(153, 0, 255));
        answerA7.setText("RADIUM");
        answerA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerA7ActionPerformed(evt);
            }
        });

        answerA8.setBackground(new java.awt.Color(255, 255, 255));
        answerA8.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerA8.setForeground(new java.awt.Color(153, 0, 255));
        answerA8.setText("PHOSPHORUS");
        answerA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerA8ActionPerformed(evt);
            }
        });

        answerA9.setBackground(new java.awt.Color(255, 255, 255));
        answerA9.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerA9.setForeground(new java.awt.Color(153, 0, 255));
        answerA9.setText("BARIUM");
        answerA9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerA9ActionPerformed(evt);
            }
        });

        answerA10.setBackground(new java.awt.Color(255, 255, 255));
        answerA10.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerA10.setForeground(new java.awt.Color(153, 51, 255));
        answerA10.setText("HELIUM");
        answerA10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerA10ActionPerformed(evt);
            }
        });

        answerB1.setBackground(new java.awt.Color(255, 255, 255));
        answerB1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerB1.setForeground(new java.awt.Color(153, 0, 255));
        answerB1.setText("Potassium");
        answerB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerB1ActionPerformed(evt);
            }
        });

        answerB2.setBackground(new java.awt.Color(255, 255, 255));
        answerB2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerB2.setForeground(new java.awt.Color(153, 0, 255));
        answerB2.setText("ARGON");
        answerB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerB2ActionPerformed(evt);
            }
        });

        answerB3.setBackground(new java.awt.Color(255, 255, 255));
        answerB3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerB3.setForeground(new java.awt.Color(153, 0, 255));
        answerB3.setText("VANADIUM");
        answerB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerB3ActionPerformed(evt);
            }
        });

        answerB4.setBackground(new java.awt.Color(255, 255, 255));
        answerB4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerB4.setForeground(new java.awt.Color(153, 0, 255));
        answerB4.setText("COPPER");
        answerB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerB4ActionPerformed(evt);
            }
        });

        answerB5.setBackground(new java.awt.Color(255, 255, 255));
        answerB5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerB5.setForeground(new java.awt.Color(153, 51, 255));
        answerB5.setText("MERCURY");
        answerB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerB5ActionPerformed(evt);
            }
        });

        answerB6.setBackground(new java.awt.Color(255, 255, 255));
        answerB6.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerB6.setForeground(new java.awt.Color(153, 0, 255));
        answerB6.setText("CALCIUM");
        answerB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerB6ActionPerformed(evt);
            }
        });

        answerB7.setBackground(new java.awt.Color(255, 255, 255));
        answerB7.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerB7.setForeground(new java.awt.Color(153, 0, 255));
        answerB7.setText("RADON");
        answerB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerB7ActionPerformed(evt);
            }
        });

        answerB8.setBackground(new java.awt.Color(255, 255, 255));
        answerB8.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerB8.setForeground(new java.awt.Color(153, 0, 255));
        answerB8.setText("POTASSIUM");
        answerB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerB8ActionPerformed(evt);
            }
        });

        answerB9.setBackground(new java.awt.Color(255, 255, 255));
        answerB9.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerB9.setForeground(new java.awt.Color(153, 0, 255));
        answerB9.setText("BISMUTH");
        answerB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerB9ActionPerformed(evt);
            }
        });

        answerB10.setBackground(new java.awt.Color(255, 255, 255));
        answerB10.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerB10.setForeground(new java.awt.Color(153, 51, 255));
        answerB10.setText("MERCURY");
        answerB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerB10ActionPerformed(evt);
            }
        });

        answerC1.setBackground(new java.awt.Color(255, 255, 255));
        answerC1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerC1.setForeground(new java.awt.Color(153, 0, 255));
        answerC1.setText("Neon");
        answerC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerC1ActionPerformed(evt);
            }
        });

        answerC2.setBackground(new java.awt.Color(255, 255, 255));
        answerC2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerC2.setForeground(new java.awt.Color(153, 0, 255));
        answerC2.setText("GOLD");
        answerC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerC2ActionPerformed(evt);
            }
        });

        answerC3.setBackground(new java.awt.Color(255, 255, 255));
        answerC3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerC3.setForeground(new java.awt.Color(153, 0, 255));
        answerC3.setText("TITANIUM");
        answerC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerC3ActionPerformed(evt);
            }
        });

        answerC4.setBackground(new java.awt.Color(255, 255, 255));
        answerC4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerC4.setForeground(new java.awt.Color(153, 0, 255));
        answerC4.setText("COBALT");
        answerC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerC4ActionPerformed(evt);
            }
        });

        answerC5.setBackground(new java.awt.Color(255, 255, 255));
        answerC5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerC5.setForeground(new java.awt.Color(153, 51, 255));
        answerC5.setText("MANGANESE");
        answerC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerC5ActionPerformed(evt);
            }
        });

        answerC6.setBackground(new java.awt.Color(255, 255, 255));
        answerC6.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerC6.setForeground(new java.awt.Color(153, 0, 255));
        answerC6.setText("COPERNICIUM");
        answerC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerC6ActionPerformed(evt);
            }
        });

        answerC7.setBackground(new java.awt.Color(255, 255, 255));
        answerC7.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerC7.setForeground(new java.awt.Color(153, 0, 255));
        answerC7.setText("RHODIUM");
        answerC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerC7ActionPerformed(evt);
            }
        });

        answerC8.setBackground(new java.awt.Color(255, 255, 255));
        answerC8.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerC8.setForeground(new java.awt.Color(153, 0, 255));
        answerC8.setText("LEAD");
        answerC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerC8ActionPerformed(evt);
            }
        });

        answerC9.setBackground(new java.awt.Color(255, 255, 255));
        answerC9.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerC9.setForeground(new java.awt.Color(153, 0, 255));
        answerC9.setText("BERYLLIUM");
        answerC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerC9ActionPerformed(evt);
            }
        });

        answerC10.setBackground(new java.awt.Color(255, 255, 255));
        answerC10.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerC10.setForeground(new java.awt.Color(153, 51, 255));
        answerC10.setText("HYDROGEN");
        answerC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerC10ActionPerformed(evt);
            }
        });

        answrD1.setBackground(new java.awt.Color(255, 255, 255));
        answrD1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answrD1.setForeground(new java.awt.Color(153, 0, 255));
        answrD1.setText("Gold");
        answrD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answrD1ActionPerformed(evt);
            }
        });

        answerD2.setBackground(new java.awt.Color(255, 255, 255));
        answerD2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answerD2.setForeground(new java.awt.Color(153, 0, 255));
        answerD2.setText("ALUMINUM");
        answerD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerD2ActionPerformed(evt);
            }
        });

        answrD3.setBackground(new java.awt.Color(255, 255, 255));
        answrD3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answrD3.setForeground(new java.awt.Color(153, 0, 255));
        answrD3.setText("TUNGSTEN");
        answrD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answrD3ActionPerformed(evt);
            }
        });

        answrD4.setBackground(new java.awt.Color(255, 255, 255));
        answrD4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answrD4.setForeground(new java.awt.Color(153, 0, 255));
        answrD4.setText("CARBON");
        answrD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answrD4ActionPerformed(evt);
            }
        });

        answrD5.setBackground(new java.awt.Color(255, 255, 255));
        answrD5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answrD5.setForeground(new java.awt.Color(153, 51, 255));
        answrD5.setText("MOLYBDENUM");
        answrD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answrD5ActionPerformed(evt);
            }
        });

        answrD6.setBackground(new java.awt.Color(255, 255, 255));
        answrD6.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answrD6.setForeground(new java.awt.Color(153, 0, 255));
        answrD6.setText("CHROMIUM");
        answrD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answrD6ActionPerformed(evt);
            }
        });

        answrD7.setBackground(new java.awt.Color(255, 255, 255));
        answrD7.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answrD7.setForeground(new java.awt.Color(153, 0, 255));
        answrD7.setText("RUBIDIUM");
        answrD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answrD7ActionPerformed(evt);
            }
        });

        answrD8.setBackground(new java.awt.Color(255, 255, 255));
        answrD8.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answrD8.setForeground(new java.awt.Color(153, 0, 255));
        answrD8.setText("PLATINUM");
        answrD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answrD8ActionPerformed(evt);
            }
        });

        answrD9.setBackground(new java.awt.Color(255, 255, 255));
        answrD9.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answrD9.setForeground(new java.awt.Color(153, 0, 255));
        answrD9.setText("BORON");
        answrD9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answrD9ActionPerformed(evt);
            }
        });

        answrD10.setBackground(new java.awt.Color(255, 255, 255));
        answrD10.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 15)); // NOI18N
        answrD10.setForeground(new java.awt.Color(153, 51, 255));
        answrD10.setText("MAGNESIUM");
        answrD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answrD10ActionPerformed(evt);
            }
        });

        ranking.setColumns(20);
        ranking.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        ranking.setForeground(new java.awt.Color(153, 51, 255));
        ranking.setRows(5);
        jScrollPane1.setViewportView(ranking);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 255));
        jLabel3.setText(" Name: ");
        jLabel3.setOpaque(true);

        nameBox.setForeground(new java.awt.Color(153, 0, 255));
        nameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBoxActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 255));
        jButton1.setText("SCORES:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question4)
                            .addComponent(answrD4)
                            .addComponent(answerC4)
                            .addComponent(answerB4)
                            .addComponent(answerA4))
                        .addGap(222, 222, 222)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answrD9)
                            .addComponent(answerB9)
                            .addComponent(answerC9)
                            .addComponent(question9)
                            .addComponent(answerA9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question1)
                            .addComponent(answerB1)
                            .addComponent(answerA1)
                            .addComponent(answerC1)
                            .addComponent(answrD1)
                            .addComponent(question3)
                            .addComponent(answerA3)
                            .addComponent(answerB3)
                            .addComponent(answrD3)
                            .addComponent(answerC3))
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(answerA6)
                                        .addComponent(answerC6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(answrD6)
                                    .addComponent(question8)
                                    .addComponent(answerB6)
                                    .addComponent(answerB7)
                                    .addComponent(answerC7)
                                    .addComponent(answerA7)
                                    .addComponent(answrD7)
                                    .addComponent(question7)
                                    .addComponent(answrD8)
                                    .addComponent(answerC8)
                                    .addComponent(question6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(question5)
                                            .addComponent(question10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(answerC10)
                                                .addComponent(answerB10, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(answerA10, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(answerA5)
                                            .addComponent(answerB5)
                                            .addComponent(answerC5)
                                            .addComponent(answrD5)
                                            .addComponent(answrD10))
                                        .addContainerGap(86, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(170, 170, 170))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(answerB8)
                                    .addComponent(answerA8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerA2)
                            .addComponent(answerB2)
                            .addComponent(answerC2)
                            .addComponent(answerD2)
                            .addComponent(question2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question1)
                    .addComponent(question6)
                    .addComponent(question5))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(question7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerA7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerB7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerC7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answrD7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answerA1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(answerB6)
                                    .addComponent(answerB1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(answerC1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(answrD1)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(answerA6)
                                    .addComponent(answerA5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(answerB5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(answerC5)
                                    .addComponent(answerC6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(answrD6)
                                        .addGap(18, 18, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(answrD5)
                                        .addGap(14, 14, 14)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(question2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(answerA2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(answerB2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(answerC2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(answerD2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(question10)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(answerA10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(answerB10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(answerC10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(answrD10))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(question3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(answerA3)
                                    .addComponent(answerA8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(answerB3)
                                    .addComponent(answerB8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(answerC8)
                                    .addComponent(answerC3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(answrD3)
                                    .addComponent(answrD8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(question9)
                                    .addComponent(question4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(answerA9)
                                    .addComponent(answerA4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(answerB9)
                                    .addComponent(answerB4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(answerC9)
                                    .addComponent(answerC4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(answrD9)
                                    .addComponent(answrD4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerC1ActionPerformed
        question1.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerC1ActionPerformed

    private void answerC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerC2ActionPerformed
        question2.setBackground(Color.green);
        score += 10;
    }//GEN-LAST:event_answerC2ActionPerformed

    private void answerC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerC3ActionPerformed
        question3.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerC3ActionPerformed

    private void answerC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerC4ActionPerformed
        question4.setBackground(Color.green);
        score += 10;
    }//GEN-LAST:event_answerC4ActionPerformed

    private void answerC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerC5ActionPerformed
        question5.setBackground(Color.green);
        score += 10;
    }//GEN-LAST:event_answerC5ActionPerformed

    private void answerC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerC6ActionPerformed
        question6.setBackground(Color.green);
        score += 10;
    }//GEN-LAST:event_answerC6ActionPerformed

    private void answerC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerC7ActionPerformed
        question7.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerC7ActionPerformed

    private void answerC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerC8ActionPerformed
        question8.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerC8ActionPerformed

    private void answerC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerC9ActionPerformed
        question9.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerC9ActionPerformed

    private void answerC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerC10ActionPerformed
        question10.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerC10ActionPerformed

    private void answrD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answrD1ActionPerformed
        question1.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answrD1ActionPerformed

    private void answerD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerD2ActionPerformed
        question2.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerD2ActionPerformed

    private void answrD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answrD3ActionPerformed
        question3.setBackground(Color.green);
        score += 10;
    }//GEN-LAST:event_answrD3ActionPerformed

    private void answrD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answrD4ActionPerformed
        question4.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answrD4ActionPerformed

    private void answrD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answrD5ActionPerformed
        question5.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answrD5ActionPerformed

    private void answrD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answrD6ActionPerformed
        question6.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answrD6ActionPerformed

    private void answrD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answrD7ActionPerformed
        question7.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answrD7ActionPerformed

    private void answrD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answrD8ActionPerformed
        question8.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answrD8ActionPerformed

    private void answrD9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answrD9ActionPerformed
        question9.setBackground(Color.green);
        score += 10;
    }//GEN-LAST:event_answrD9ActionPerformed

    private void answrD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answrD10ActionPerformed
        question10.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answrD10ActionPerformed

    private void answerA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerA1ActionPerformed
        question1.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerA1ActionPerformed

    private void answerA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerA2ActionPerformed
        question2.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerA2ActionPerformed

    private void answerA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerA5ActionPerformed
        question5.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerA5ActionPerformed

    private void answerA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerA8ActionPerformed
        question8.setBackground(Color.green);
        score += 10;
    }//GEN-LAST:event_answerA8ActionPerformed

    private void answerB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerB1ActionPerformed
        question1.setBackground(Color.green);
        score += 10;
    }//GEN-LAST:event_answerB1ActionPerformed

    private void answerB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerB2ActionPerformed
        question2.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerB2ActionPerformed

    private void answerA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerA3ActionPerformed
        question3.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerA3ActionPerformed

    private void answerB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerB3ActionPerformed
        question3.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerB3ActionPerformed

    private void answerA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerA4ActionPerformed
        question4.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerA4ActionPerformed

    private void answerB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerB4ActionPerformed
        question4.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerB4ActionPerformed

    private void answerB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerB5ActionPerformed
        question5.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerB5ActionPerformed

    private void answerA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerA6ActionPerformed
        question6.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerA6ActionPerformed

    private void answerB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerB6ActionPerformed
        question6.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerB6ActionPerformed

    private void answerA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerA7ActionPerformed
        question7.setBackground(Color.green);
        score += 10;     
    }//GEN-LAST:event_answerA7ActionPerformed

    private void answerB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerB7ActionPerformed
        question7.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerB7ActionPerformed

    private void answerB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerB8ActionPerformed
        question8.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerB8ActionPerformed

    private void answerA9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerA9ActionPerformed
        question9.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerA9ActionPerformed

    private void answerB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerB9ActionPerformed
        question9.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerB9ActionPerformed

    private void answerA10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerA10ActionPerformed
        question10.setBackground(Color.red);
        score -= 10;
    }//GEN-LAST:event_answerA10ActionPerformed

    private void answerB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerB10ActionPerformed
        question10.setBackground(Color.green);
        score += 10;
    }//GEN-LAST:event_answerB10ActionPerformed

    private void nameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBoxActionPerformed
        
    }//GEN-LAST:event_nameBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = (nameBox.getText());
        ranking.setText(name + ": " + score);
        
        String pathname = "scores.txt";
        File file = new File(pathname);
        PrintWriter output = null;
        try {
           output = new PrintWriter(file);
        }
        catch (FileNotFoundException ex) {
           System.out.println("Cannot create " + pathname);
           System.exit(1);  // quit the program
        }
        output.print(ranking.getText());
        output.close();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void rankingActionPerformed(java.awt.event.ActionEvent evt) {
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalityQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalityQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalityQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalityQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalityQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerA1;
    private javax.swing.JButton answerA10;
    private javax.swing.JButton answerA2;
    private javax.swing.JButton answerA3;
    private javax.swing.JButton answerA4;
    private javax.swing.JButton answerA5;
    private javax.swing.JButton answerA6;
    private javax.swing.JButton answerA7;
    private javax.swing.JButton answerA8;
    private javax.swing.JButton answerA9;
    private javax.swing.JButton answerB1;
    private javax.swing.JButton answerB10;
    private javax.swing.JButton answerB2;
    private javax.swing.JButton answerB3;
    private javax.swing.JButton answerB4;
    private javax.swing.JButton answerB5;
    private javax.swing.JButton answerB6;
    private javax.swing.JButton answerB7;
    private javax.swing.JButton answerB8;
    private javax.swing.JButton answerB9;
    private javax.swing.JButton answerC1;
    private javax.swing.JButton answerC10;
    private javax.swing.JButton answerC2;
    private javax.swing.JButton answerC3;
    private javax.swing.JButton answerC4;
    private javax.swing.JButton answerC5;
    private javax.swing.JButton answerC6;
    private javax.swing.JButton answerC7;
    private javax.swing.JButton answerC8;
    private javax.swing.JButton answerC9;
    private javax.swing.JButton answerD2;
    private javax.swing.JButton answrD1;
    private javax.swing.JButton answrD10;
    private javax.swing.JButton answrD3;
    private javax.swing.JButton answrD4;
    private javax.swing.JButton answrD5;
    private javax.swing.JButton answrD6;
    private javax.swing.JButton answrD7;
    private javax.swing.JButton answrD8;
    private javax.swing.JButton answrD9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameBox;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question10;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question5;
    private javax.swing.JLabel question6;
    private javax.swing.JLabel question7;
    private javax.swing.JLabel question8;
    private javax.swing.JLabel question9;
    private javax.swing.JTextArea ranking;
    // End of variables declaration//GEN-END:variables
}
